settings:
  view: yes
  name: Settings
  icon: mdi:settings
  entities:
      - sensor.uptime
      - group.weather
      - group.energy
      - group.travis
      - group.Automation_Group
      - group.pagebutton
      - group.input_slider
      - input_boolean.alert_mode
