  - alias: Sunrise
    trigger:
      platform: sun
      event: sunrise
      offset: "-00:45:00"
    action:
      service: homeassistant.turn_off
      entity_id: input_boolean.trigger_bedtime
      service: homeassistant.turn_on
      entity_id: input_boolean.trigger_first_light

  - alias: Sunset Trigger
    trigger:
      platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: -2.5
    action:
      service: homeassistant.turn_off
      entity_id: input_boolean.trigger_first_light
      service: homeassistant.turn_on
      entity_id: input_boolean.trigger_last_light


  - alias: Goodnight
    trigger:
      platform: time
      at: '22:30:00'
    action:
      service: homeassistant.turn_off
      entity_id: input_boolean.trigger_last_light
      service: homeassistant.turn_on
      entity_id: input_boolean.trigger_bedtime


  - alias: Last_Light
    trigger:
      platform: state
      entity_id: input_boolean.trigger_last_light
      to: 'on'
    action:
      service: scene.turn_on
      entity_id: scene.evening

  - alias: First_Light
    trigger:
      platform: state
      entity_id: input_boolean.trigger_first_light
      to: 'on'
    action:
      service: scene.turn_on
      entity_id: scene.morning

  - alias: First_Light
    trigger:
      platform: state
      entity_id: input_boolean.trigger_bedtime
      to: 'on'
    action:
      service: scene.turn_on
      entity_id: scene.off_to_bed

# Scenes
scene:
  - name: evening
    entities:
      group.security_lights
        state: on
      switch.Piano_Back
        state: on
      switch.Piano_Front
        state: on
      switch.Dining_Room
        state: on

  - name: morning
    entities:
      group.security_lights
        state: off
      switch.Piano_Back
        state: off
      switch.Piano_Front
        state: off
      switch.Dining_Room
        state: off

  - name: Off To Bed
    entities:
        state: off
      switch.Piano_Back
        state: off
      switch.Piano_Front
        state: off
      switch.Dining_Room
        state: off
      switch.Dining_Room
        state: off
      switch.Basement_Switch
        state: off
      switch.Sunroom
        state: off
