  - alias: Sunrise
    trigger:
      platform: sun
      event: sunrise
      offset: "-00:45:00"
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.trigger_bedtime
      - service: homeassistant.turn_on
        entity_id: input_boolean.trigger_first_light

  - alias: Sunset Trigger
    trigger:
      - platform: numeric_state
        entity_id: sun.sun
        value_template: '{{ state.attributes.elevation }}'
        below: -2.5
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.trigger_first_light
      - service: homeassistant.turn_on
        entity_id: input_boolean.trigger_last_light

  - alias: Goodnight
    trigger:
      platform: time
      at: '22:30:00'
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.trigger_last_light
      - service: homeassistant.turn_on
        entity_id: input_boolean.trigger_bedtime


  - alias: Last_Light
    trigger:
      - platform: state
        entity_id: input_boolean.trigger_last_light
        to: 'on'
    action:
      - service: switch.turn_on
        entity_id:
          - group.security_lights
          - switch.Piano_Back
          - switch.Piano_Front
          - switch.Dining_Room

  - alias: First_Light
    trigger:
      - platform: state
        entity_id: input_boolean.trigger_first_light
        to: 'on'
    action:
      - service: switch.turn_off
        entity_id:
          - group.security_lights
          - switch.Piano_Back
          - switch.Piano_Front
          - switch.Dining_Room

  - alias: Bedtime
    trigger:
      - platform: state
        entity_id: input_boolean.trigger_bedtime
        to: 'on'
    action:
      - service: switch.turn_off
        entity_id:
            - switch.Piano_Back
            - switch.Piano_Front
            - switch.Dining_Room
            - switch.Basement_Switch
            - switch.Sunroom
