homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 81
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Customization file
  customize: !include_dir_merge_named customize

# Enables the frontend
frontend:
# Enables configuration UI
config:

http:
  base_url: !secret http_url
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  # Uncomment this to add a password (recommended!)
  api_password: !secret api_password

updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Track the sun
sun:

arlo:
  username: !secret gmail_username
  password: !secret E_password

# Text to speech
tts:
  - platform: google

ring:
  username: !secret outlook_username
  password: !secret E_password

mqtt:
  discovery: true
  discovery_prefix: homeassistant

splunk:
  token: !secret splunk_token
  host: !secret splunk_ip
 #source="http:hassio 2" (index="homeassistant")

device_tracker:
  - platform: owntracks_http

netatmo:
  api_key: !secret netamo_api_key
  secret_key: !secret netamo_secret_key
  username: !secret outlook_username
  password: !secret E_password
  discovery: true

cover:
  - platform: myq
    username: !secret outlook_username
    password: !secret E_password
    type: chamberlain

panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml

ffmpeg:

media_player:
  - platform: spotify
    client_id: !secret spotify_client_ID
    client_secret: !secret spotify_client_secret

notify:
  - name: my_pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_key

google_assistant:
  project_id: hertz-automation
  client_id: !secret Google_Assistant_ClientID
  access_token: !secret Google_Assistant_access_token
  exposed_domains:
    - switch
    - light
    - cover


#microsoft_face:
#  api_key: !secret api_face
#  azure_region: eastus

#image_processing:
#  - platform: microsoft_face_detect
#    name: face_dectect
#    source:
#      - entity_id: camera.foscam
#  - platform: microsoft_face_identify
#    name: face_identify
#    group: family
#    source:
#      - entity_id: camera.foscam

dialogflow:

intent_script:
  getTempOffice:
    speech:
      text: The temperature in the office {{ states('sensor.office_temp') }} degrees
input_text:
  haswitchplate_pagebutton1_label:
    name: HASP Page Button 1 Label
    icon: mdi:book-open-page-variant
  haswitchplate_pagebutton2_label:
    name: HASP Page Button 2 Label
    icon: mdi:book-open-page-variant
  haswitchplate_pagebutton3_label:
    name: HASP Page Button 3 Label
    icon: mdi:book-open-page-variant
input_number:
  haswitchplate_pagebutton1_page:
    name: HASP Page Button 1 Page
    icon: mdi:format-list-numbers
    min: 0
    max: 9
    step: 1
  haswitchplate_pagebutton2_page:
    name: HASP Page Button 2 Page
    icon: mdi:format-list-numbers
    min: 0
    max: 9
    step: 1
  haswitchplate_pagebutton3_page:
    name: HASP Page Button 3 Page
    icon: mdi:format-list-numbers
    min: 0
    max: 9
    step: 1
  haswitchplate_active_page:
    name: HASP Active Page
    icon: mdi:format-list-numbers
    min: 0
    max: 9
    step: 1
  haswitchplate_alarmcode1:
    name: AlarmCode1
    icon: mdi:format-list-numbers
    min: -1
    max: 9
    step: 1
    initial: -1
  haswitchplate_alarmcode2:
    name: AlarmCode2
    icon: mdi:format-list-numbers
    min: -1
    max: 9
    step: 1
    initial: -1
  haswitchplate_alarmcode3:
    name: AlarmCode3
    icon: mdi:format-list-numbers
    min: -1
    max: 9
    step: 1
    initial: -1
  haswitchplate_alarmcode4:
    name: AlarmCode4
    icon: mdi:format-list-numbers
    min: -1
    max: 9
    step: 1
    initial: -1

group: !include_dir_merge_named group
automation: !include_dir_merge_list automation
input_boolean: !include input_booleans.yaml
script: !include_dir_merge_named script
zone: !include zones.yaml
sensor: !include sensors.yaml
camera: !include cameras.yaml
binary_sensor: !include binary_sensors.yaml
switch: !include switches.yaml
history: !include history.yaml
logbook: !include logbook.yaml
scene: !include_dir_merge_list scenes/
