- alias: HASwitchPlate_Weather
  trigger:
  - platform: state
    entity_id: sensor.dark_sky_temperature
  - platform: mqtt
    topic: 'homeassistant/binary_sensor/HASwitchPlate/state'
    payload: 'ON'
  - platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[2].b[6].font'
      payload: '3'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[2].b[6].txt'
      payload_template: '"{{states.sensor.dark_sky_temperature.state}}F"'
      retain: true
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[2].b[7].font'
      payload_template: '{% if states.sensor.dark_sky_summary.state|length <= 6 -%}3{% elif (states.sensor.dark_sky_summary.state|length > 6) and (states.sensor.dark_sky_summary.state|length <= 10) %}2{% elif (states.sensor.dark_sky_summary.state|length > 10) and (states.sensor.dark_sky_summary.state|length <= 15) %}1{% else %}0{%- endif %}'
      retain: true
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[2].b[7].txt'
      payload_template: '"{{states.sensor.dark_sky_summary.state|wordwrap(20, wrapstring="\\r")}}"'
      retain: true
