- alias: HASwitchPlate_Scenes_Init
  trigger:
  - platform: mqtt
    topic: 'homeassistant/binary_sensor/HASwitchPlate/state'
    payload: 'ON'
  - platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[1].b[4].font'
      payload: '2'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[1].b[4].txt'
      payload: '"Lights On"'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[1].b[5].font'
      payload: '2'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[1].b[5].txt'
      payload: '"Daylight"'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[1].b[6].font'
      payload: '2'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[1].b[6].txt'
      payload: '"Night"'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[1].b[7].font'
      payload: '2'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[1].b[7].txt'
      payload: '"Lights Off"'

- alias: HASwitchPlate_SceneButton4
  trigger:
    platform: mqtt
    topic: 'homeassistant/haswitchplate/HASwitchPlate/state/p[1].b[4]'
    payload: 'ON'
  action:
    service: scene.turn_on
    entity_id: scene.lights_on

- alias: HASwitchPlate_SceneButton5
  trigger:
    platform: mqtt
    topic: 'homeassistant/haswitchplate/HASwitchPlate/state/p[1].b[5]'
    payload: 'ON'
  action:
    service: scene.turn_on
    entity_id: scene.daylight

- alias: HASwitchPlate_SceneButton6
  trigger:
    platform: mqtt
    topic: 'homeassistant/haswitchplate/HASwitchPlate/state/p[1].b[6]'
    payload: 'ON'
  action:
    service: scene.turn_on
    entity_id: scene.night

- alias: HASwitchPlate_SceneButton7
  trigger:
    platform: mqtt
    topic: 'homeassistant/haswitchplate/HASwitchPlate/state/p[1].b[7]'
    payload: 'ON'
  action:
    service: scene.turn_on
    entity_id: scene.lights_off
