##############################################################################
# Automations for handling the 3 page select buttons at the bottom of each
# page on the panel.  This example should be ready to use, simply run a
# Case Sensitive search/replace on "HASwitchPlate" with your node name

##############################################################################
# Initialize device on connect
- alias: HASwitchPlate_Connected
  trigger:
  - platform: mqtt
    topic: 'homeassistant/binary_sensor/HASwitchPlate/state'
    payload: 'ON'
  - platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data_template:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/page'
      payload_template: '{{states.input_number.haswitchplate_active_page.state|int}}'

##############################################################################
# select haswitchplate_pagebutton1_page in response to page button 1
- alias: HASwitchPlate_PageButton1_Action
  trigger:
  - platform: mqtt
    topic: 'homeassistant/haswitchplate/HASwitchPlate/state/+'
    payload: 'ON'
  condition:
    condition: template
    value_template: '{{ trigger.topic.split("/")[-1].split("].b[")[1].strip("]")|int == 1 }}'
  action:
  - service: mqtt.publish
    data_template:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/page'
      payload_template: "{{states.input_number.haswitchplate_pagebutton1_page.state|int}}"

##############################################################################
# select haswitchplate_pagebutton2_page in response to page button 2
- alias: HASwitchPlate_PageButton2_Action
  trigger:
  - platform: mqtt
    topic: 'homeassistant/haswitchplate/HASwitchPlate/state/+'
    payload: 'ON'
  condition:
    condition: template
    value_template: '{{ trigger.topic.split("/")[-1].split("].b[")[1].strip("]")|int == 2 }}'
  action:
  - service: mqtt.publish
    data_template:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/page'
      payload_template: "{{states.input_number.haswitchplate_pagebutton2_page.state|int}}"

##############################################################################
# select haswitchplate_pagebutton3_page in response to page button 3
- alias: HASwitchPlate_PageButton3_Action
  trigger:
  - platform: mqtt
    topic: 'homeassistant/haswitchplate/HASwitchPlate/state/+'
    payload: 'ON'
  condition:
    condition: template
    value_template: '{{ trigger.topic.split("/")[-1].split("].b[")[1].strip("]")|int == 3 }}'
  action:
  - service: mqtt.publish
    data_template:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/page'
      payload_template: "{{states.input_number.haswitchplate_pagebutton3_page.state|int}}"

##############################################################################
# Update haswitchplate_active_page when changed at the panel
- alias: HASwitchPlate_Panel_Page_Changed
  trigger:
  - platform: mqtt
    topic: 'homeassistant/haswitchplate/HASwitchPlate/state/page'
  action:
  - service: automation.turn_off
    entity_id: automation.haswitchplate_active_page_slider_changed
  - service: input_number.set_value
    data_template:
      entity_id: input_number.haswitchplate_active_page
      value: '{{ trigger.payload }}'
  - service: automation.turn_on
    entity_id: automation.haswitchplate_active_page_slider_changed

##############################################################################
# Change page at panel when haswitchplate_active_page updated
- alias: HASwitchPlate_Active_Page_Slider_Changed
  trigger:
    platform: state
    entity_id: input_number.haswitchplate_active_page
  action:
    service: mqtt.publish
    data_template:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/page'
      payload: '{{ states.input_number.haswitchplate_active_page.state | int }}'

##############################################################################
# Set page button text across all pages to the value selected in the interface

# set page button text on each page to haswitchplate_pagebutton1_label
- alias: HASwitchPlate_PageButton1_Text
  trigger:
  - platform: state
    entity_id: input_text.haswitchplate_pagebutton1_label
  - platform: mqtt
    topic: 'homeassistant/binary_sensor/HASwitchPlate/state'
    payload: 'ON'
  - platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[1].b[1].txt'
      payload_template: '"{{states.input_text.haswitchplate_pagebutton1_label.state}}"'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[2].b[1].txt'
      payload_template: '"{{states.input_text.haswitchplate_pagebutton1_label.state}}"'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[3].b[1].txt'
      payload_template: '"{{states.input_text.haswitchplate_pagebutton1_label.state}}"'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[4].b[1].txt'
      payload_template: '"{{states.input_text.haswitchplate_pagebutton1_label.state}}"'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[5].b[1].txt'
      payload_template: '"{{states.input_text.haswitchplate_pagebutton1_label.state}}"'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[6].b[1].txt'
      payload_template: '"{{states.input_text.haswitchplate_pagebutton1_label.state}}"'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[1].txt'
      payload_template: '"{{states.input_text.haswitchplate_pagebutton1_label.state}}"'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[8].b[1].txt'
      payload_template: '"{{states.input_text.haswitchplate_pagebutton1_label.state}}"'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[9].b[1].txt'
      payload_template: '"{{states.input_text.haswitchplate_pagebutton1_label.state}}"'

# set page button text on each page to haswitchplate_pagebutton2_label
- alias: HASwitchPlate_PageButton2_Text
  trigger:
  - platform: state
    entity_id: input_text.haswitchplate_pagebutton2_label
  - platform: mqtt
    topic: 'homeassistant/binary_sensor/HASwitchPlate/state'
    payload: 'ON'
  - platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[1].b[2].txt'
      payload_template: '"{{states.input_text.haswitchplate_pagebutton2_label.state}}"'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[2].b[2].txt'
      payload_template: '"{{states.input_text.haswitchplate_pagebutton2_label.state}}"'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[3].b[2].txt'
      payload_template: '"{{states.input_text.haswitchplate_pagebutton2_label.state}}"'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[4].b[2].txt'
      payload_template: '"{{states.input_text.haswitchplate_pagebutton2_label.state}}"'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[5].b[2].txt'
      payload_template: '"{{states.input_text.haswitchplate_pagebutton2_label.state}}"'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[6].b[2].txt'
      payload_template: '"{{states.input_text.haswitchplate_pagebutton2_label.state}}"'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[2].txt'
      payload_template: '"{{states.input_text.haswitchplate_pagebutton2_label.state}}"'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[8].b[2].txt'
      payload_template: '"{{states.input_text.haswitchplate_pagebutton2_label.state}}"'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[9].b[2].txt'
      payload_template: '"{{states.input_text.haswitchplate_pagebutton2_label.state}}"'

# set page button text on each page to haswitchplate_pagebutton3_label
- alias: HASwitchPlate_PageButton3_Text
  trigger:
  - platform: state
    entity_id: input_text.haswitchplate_pagebutton3_label
  - platform: mqtt
    topic: 'homeassistant/binary_sensor/HASwitchPlate/state'
    payload: 'ON'
  - platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[1].b[3].txt'
      payload_template: '"{{states.input_text.haswitchplate_pagebutton3_label.state}}"'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[2].b[3].txt'
      payload_template: '"{{states.input_text.haswitchplate_pagebutton3_label.state}}"'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[3].b[3].txt'
      payload_template: '"{{states.input_text.haswitchplate_pagebutton3_label.state}}"'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[4].b[3].txt'
      payload_template: '"{{states.input_text.haswitchplate_pagebutton3_label.state}}"'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[5].b[3].txt'
      payload_template: '"{{states.input_text.haswitchplate_pagebutton3_label.state}}"'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[6].b[3].txt'
      payload_template: '"{{states.input_text.haswitchplate_pagebutton3_label.state}}"'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[3].txt'
      payload_template: '"{{states.input_text.haswitchplate_pagebutton3_label.state}}"'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[8].b[3].txt'
      payload_template: '"{{states.input_text.haswitchplate_pagebutton3_label.state}}"'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[9].b[3].txt'
      payload_template: '"{{states.input_text.haswitchplate_pagebutton3_label.state}}"'

##############################################################################
# Set page button colors across selected pages to show active page button
- alias: HASwitchPlate_PageButton_Colors
  trigger:
  - platform: state
    entity_id: input_number.haswitchplate_pagebutton1_page
  - platform: state
    entity_id: input_number.haswitchplate_pagebutton2_page
  - platform: state
    entity_id: input_number.haswitchplate_pagebutton3_page
  - platform: state
    entity_id: input_number.haswitchplate_active_page
  - platform: mqtt
    topic: 'homeassistant/binary_sensor/HASwitchPlate/state'
    payload: 'ON'
  - platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data_template:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[{{states.input_number.haswitchplate_active_page.state|int}}].b[1].bco'
      payload_template: >-
        {% if states.input_number.haswitchplate_active_page.state|int == states.input_number.haswitchplate_pagebutton1_page.state|int -%}
          65535
        {%- else -%}
          25388
        {%- endif %}
  - service: mqtt.publish
    data_template:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[{{states.input_number.haswitchplate_active_page.state|int}}].b[1].pco'
      payload_template: >-
        {% if states.input_number.haswitchplate_active_page.state|int == states.input_number.haswitchplate_pagebutton1_page.state|int -%}
          0
        {%- else -%}
          65535
        {%- endif %}
  - service: mqtt.publish
    data_template:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[{{states.input_number.haswitchplate_active_page.state|int}}].b[2].bco'
      payload_template: >-
        {% if states.input_number.haswitchplate_active_page.state|int == states.input_number.haswitchplate_pagebutton2_page.state|int -%}
          65535
        {%- else -%}
          25388
        {%- endif %}
  - service: mqtt.publish
    data_template:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[{{states.input_number.haswitchplate_active_page.state|int}}].b[2].pco'
      payload_template: >-
        {% if states.input_number.haswitchplate_active_page.state|int == states.input_number.haswitchplate_pagebutton2_page.state|int -%}
         0
        {%- else -%}
          65535
        {%- endif %}
  - service: mqtt.publish
    data_template:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[{{states.input_number.haswitchplate_active_page.state|int}}].b[3].bco'
      payload_template: >-
        {% if states.input_number.haswitchplate_active_page.state|int == states.input_number.haswitchplate_pagebutton3_page.state|int -%}
          65535
        {%- else -%}
          25388
        {%- endif %}
  - service: mqtt.publish
    data_template:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[{{states.input_number.haswitchplate_active_page.state|int}}].b[3].pco'
      payload_template: >-
        {% if states.input_number.haswitchplate_active_page.state|int == states.input_number.haswitchplate_pagebutton3_page.state|int -%}
          0
        {%- else -%}
          65535
        {%- endif %}
