- alias: HASwitchPlate_Controls_B10
  trigger:
  - platform: mqtt
    topic: 'homeassistant/binary_sensor/HASwitchPlate/state'
    payload: 'ON'
  - platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[6].b[10].txt'
      payload_template: '"MainFloor"'
      retain: true
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[6].b[10].font'
      payload_template: '0'
      retain: true

- alias: HASwitchPlate_Controls_Button_10_On
  trigger:
    platform: mqtt
    topic: 'homeassistant/haswitchplate/HASwitchPlate/state/p[6].b[10]'
    payload: 'ON'
  condition:
    condition: state
    entity_id: input_boolean.controls_b10
    state: 'off'
  action:
    - service: logbook.log
      data_template:
        name: HASwitchPlate
        message: Button 10
    - service: switch.turn_on
      entity_id:
        - switch.basement_switch
        - switch.dining_room
        - switch.kitchen_back
        - switch.kitchen_front
        - switch.piano_back
        - switch.piano_front
        - switch.sunroom
    - service: mqtt.publish
      data:
        topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[6].b[10].bco'
        payload_template: '65504'
        retain: true
    - service: input_boolean.turn_on
      entity_id: input_boolean.controls_b10

- alias: HASwitchPlate_Controls_Button_10_Off
  trigger:
    platform: mqtt
    topic: 'homeassistant/haswitchplate/HASwitchPlate/state/p[6].b[10]'
    payload: 'ON'
  condition:
    condition: state
    entity_id: input_boolean.controls_b10
    state: 'on'
  action:
    - service: logbook.log
      data_template:
        name: HASwitchPlate
        message: Button 10
    - service: switch.turn_off
      entity_id:
        - switch.basement_switch
        - switch.dining_room
        - switch.kitchen_back
        - switch.kitchen_front
        - switch.piano_back
        - switch.piano_front
        - switch.sunroom
    - service: mqtt.publish
      data:
        topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[6].b[10].bco'
        payload_template: '65535'
        retain: true
    - service: input_boolean.turn_off
      entity_id: input_boolean.controls_b10
