- alias: HASwitchPlate_Controls_B11
  trigger:
  - platform: mqtt
    topic: 'homeassistant/binary_sensor/HASwitchPlate/state'
    payload: 'ON'
  - platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[6].b[11].txt'
      payload_template: '"All"'
      retain: true

- alias: HASwitchPlate_Controls_Button_11_On
  trigger:
    platform: mqtt
    topic: 'homeassistant/haswitchplate/HASwitchPlate/state/p[6].b[11]'
    payload: 'ON'
  condition:
    condition: state
    entity_id: input_boolean.controls_b11
    state: 'off'
  action:
    - service: logbook.log
      data_template:
        name: HASwitchPlate
        message: Button 11
    - service: switch.turn_on
      entity_id:
        - group.main_level_group
        - group.upstairs_group
    - service: mqtt.publish
      data:
        topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[6].b[11].bco'
        payload_template: '65504'
        retain: true
    - service: input_boolean.turn_on
      entity_id: input_boolean.controls_b11

- alias: HASwitchPlate_Controls_Button_11_Off
  trigger:
    platform: mqtt
    topic: 'homeassistant/haswitchplate/HASwitchPlate/state/p[6].b[11]'
    payload: 'ON'
  condition:
    condition: state
    entity_id: input_boolean.controls_b11
    state: 'on'
  action:
    - service: logbook.log
      data_template:
        name: HASwitchPlate
        message: Button 11
    - service: switch.turn_off
      entity_id:
        - group.main_level_group
        - group.upstairs_group
    - service: mqtt.publish
      data:
        topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[6].b[11].bco'
        payload_template: '65535'
        retain: true
    - service: input_boolean.turn_off
      entity_id: input_boolean.controls_b11
