- alias: HASwitchPlate_Controls_B8
  trigger:
  - platform: mqtt
    topic: 'homeassistant/binary_sensor/HASwitchPlate/state'
    payload: 'ON'
  - platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[6].b[8].txt'
      payload_template: '"Outside"'
      retain: true
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[6].b[8].font'
      payload_template: '0'
      retain: true

- alias: HASwitchPlate_Controls_Button_8_On
  trigger:
    platform: mqtt
    topic: 'homeassistant/haswitchplate/HASwitchPlate/state/p[6].b[8]'
    payload: 'ON'
  condition:
    condition: state
    entity_id: input_boolean.controls_b8
    state: 'off'
  action:
    - service: logbook.log
      data_template:
        name: HASwitchPlate
        message: Button 8
    - service: switch.turn_on
      entity_id:
        - group.security_lights
    - service: mqtt.publish
      data:
        topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[6].b[8].bco'
        payload_template: '65504'
        retain: true
    - service: input_boolean.turn_on
      entity_id: input_boolean.controls_b8

- alias: HASwitchPlate_Controls_Button_8_Off
  trigger:
    platform: mqtt
    topic: 'homeassistant/haswitchplate/HASwitchPlate/state/p[6].b[8]'
    payload: 'ON'
  condition:
    condition: state
    entity_id: input_boolean.controls_b8
    state: 'on'
  action:
    - service: logbook.log
      data_template:
        name: HASwitchPlate
        message: Button 8
    - service: switch.turn_off
      entity_id:
        - group.security_lights
    - service: mqtt.publish
      data:
        topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[6].b[8].bco'
        payload_template: '65535'
        retain: true
    - service: input_boolean.turn_off
      entity_id: input_boolean.controls_b8

- alias: HASwitchPlate_Logic_button_8_on
  trigger:
    - platform: state
      entity_id:
        - group.security_lights
      to: 'on'
  action:
    - service: mqtt.publish
      data:
        topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[6].b[8].bco'
        payload_template: '65504'
        retain: true

- alias: HASwitchPlate_Logic_button_8_off
  trigger:
    - platform: state
      entity_id:
        - group.security_lights
      to: 'off'
  action:
    - service: mqtt.publish
      data:
        topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[6].b[8].bco'
        payload_template: '65535'
        retain: true
