- alias: HASwitchPlate_Controls_Sensors
  trigger:
  - platform: mqtt
    topic: 'homeassistant/binary_sensor/HASwitchPlate/state'
    payload: 'ON'
  - platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[6].b[6].txt'
      payload_template: '"garage: {{states.sensor.garage_temp.state }}"'
      retain: true
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[6].b[6].font'
      payload_template: '1'
      retain: true
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[6].b[7].txt'
      payload_template: '"office: {{states.sensor.office_temp.state }}"'
      retain: true
