# Button text/font
- alias: HASwitchPlate_Intercom_B10
  trigger:
  - platform: mqtt
    topic: 'homeassistant/binary_sensor/HASwitchPlate/state'
    payload: 'ON'
  - platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[10].txt'
      payload: '"Alice"'

- alias: HASwitchPlate_Alice
  trigger:
    platform: mqtt
    topic: 'homeassistant/haswitchplate/HASwitchPlate/state/p[7].b[10]'
    payload: 'ON'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.intercom_alert_mode
        state: 'on'
      - condition: state
        entity_id: input_boolean.alice
        state: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.alice
    - service: script.speech_engine
      data_template:
        Intercom: "alice, Please come to the kitchen"
