# Button text/font
- alias: HASwitchPlate_Intercom_B15
  trigger:
  - platform: mqtt
    topic: 'homeassistant/binary_sensor/HASwitchPlate/state'
    payload: 'ON'
  - platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[15].txt'
      payload: '"All"'

- alias: HASwitchPlate_All
  trigger:
    platform: mqtt
    topic: 'homeassistant/haswitchplate/HASwitchPlate/state/p[7].b[15]'
    payload: 'ON'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.intercom_alert_mode
        state: 'on'
      - condition: state
        entity_id: input_boolean.intercom_all
        state: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.intercom_all
    - service: script.speech_engine
      data_template:
        Intercom: "Everyone, please come to the Kitchen.  Everyone to the kitchen"
