# Button text/font
- alias: HASwitchPlate_Intercom_B4
  trigger:
  - platform: mqtt
    topic: 'homeassistant/binary_sensor/HASwitchPlate/state'
    payload: 'ON'
  - platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[4].txt'
      payload: '"Jackie"'

- alias: HASwitchPlate_Jackie
  trigger:
    platform: mqtt
    topic: 'homeassistant/haswitchplate/HASwitchPlate/state/p[7].b[4]'
    payload: 'ON'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.intercom_alert_mode
        state: 'on'
      - condition: state
        entity_id: input_boolean.jackie
        state: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.jackie
    - service: script.speech_engine
      data_template:
        Intercom: "Jackie, Please come to the kitchen"

- alias: HASwitchPlate_Jackie_Away
  trigger:
    platform: state
    entity_id: device_tracker.jackies_gearfit
    state: 'not_home'
  action:
    - service: mqtt.publish
      data:
        topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[4].bco'
        payload_template: '65504'
        retain: true
- alias: HASwitchPlate_Jackie_Home
  trigger:
    platform: state
    entity_id: device_tracker.jackies_gearfit
    state: 'home'
  action:
    - service: mqtt.publish
      data:
        topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[4].bco'
        payload_template: '65535'
        retain: true
