# Button text/font
- alias: HASwitchPlate_B7
  trigger:
  - platform: mqtt
    topic: 'homeassistant/binary_sensor/HASwitchPlate/state'
    payload: 'ON'
  - platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[7].txt'
      payload: '"Isaac"'

- alias: HASwitchPlate_Isaac
  trigger:
    platform: mqtt
    topic: 'homeassistant/haswitchplate/HASwitchPlate/state/p[7].b[7]'
    payload: 'ON'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.intercom_alert_mode
        state: 'on'
      - condition: state
        entity_id: input_boolean.isaac
        state: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.isaac
    - service: script.speech_engine
      data_template:
        Intercom: "Isaac, Please come to the kitchen"
- alias: HASwitchPlate_Isaac_Away
  trigger:
    platform: time
    # Matches every minute
    seconds: 30
  condition:
  - condition: state
    entity_id: 'device_tracker.isaac_presence'
    state: 'not_home'
  action:
    - service: mqtt.publish
      data:
        topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[7].bco'
        payload_template: '65504'
        retain: true
- alias: HASwitchPlate_Isaac_Home
  trigger:
    platform: time
    # Matches every minute
    seconds: 30
  condition:
  - condition: state
    entity_id: 'device_tracker.isaac_presence'
    state: 'home'
  action:
    - service: mqtt.publish
      data:
        topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[7].bco'
        payload_template: '65535'
        retain: true
