- alias: HASwitchPlate_Controls
  trigger:
  - platform: mqtt
    topic: 'homeassistant/binary_sensor/HASwitchPlate/state'
    payload: 'ON'
  - platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[6].b[8].txt'
      payload_template: '"Outside"'
      retain: true
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[6].b[9].txt'
      payload_template: '"Upstairs"'
      retain: true
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[6].b[10].txt'
      payload_template: '"MainFloor"'
      retain: true
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[6].b[11].txt'
      payload_template: '"All"'
      retain: true
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[6].b[9].font'
      payload_template: '0'
      retain: true
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[6].b[10].font'
      payload_template: '0'
      retain: true

##########################################################################
##########################################################################
##########################################################################
##########################################################################
##########################################################################
##########################################################################
- alias: HASwitchPlate_Controls_Button_8_On
  trigger:
    platform: mqtt
    topic: 'homeassistant/haswitchplate/HASwitchPlate/state/p[6].b[8]'
    payload: 'ON'
  condition:
    condition: state
    entity_id: input_boolean.controls_b8
    state: 'off'
  action:
    - service: logbook.log
      data_template:
        name: HASwitchPlate
        message: Button 8
    - service: switch.turn_on
      entity_id:
        - group.security_lights
    - service: mqtt.publish
      data:
        topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[6].b[8].bco'
        payload_template: '65504'
        retain: true
    - service: input_boolean.turn_on
      entity_id: input_boolean.controls_b8

- alias: HASwitchPlate_Controls_Button_9_On
  trigger:
    platform: mqtt
    topic: 'homeassistant/haswitchplate/HASwitchPlate/state/p[6].b[9]'
    payload: 'ON'
  condition:
    condition: state
    entity_id: input_boolean.controls_b9
    state: 'off'
  action:
    - service: logbook.log
      data_template:
        name: HASwitchPlate
        message: Button 9
    - service: switch.turn_on
      entity_id:
        - group.upstairs_lights
    - service: mqtt.publish
      data:
        topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[6].b[9].bco'
        payload_template: '65504'
        retain: true
    - service: input_boolean.turn_on
      entity_id: input_boolean.controls_b9

- alias: HASwitchPlate_Controls_Button_10_On
  trigger:
    platform: mqtt
    topic: 'homeassistant/haswitchplate/HASwitchPlate/state/p[6].b[10]'
    payload: 'ON'
  condition:
    condition: state
    entity_id: input_boolean.controls_b10
    state: 'off'
  action:
    - service: logbook.log
      data_template:
        name: HASwitchPlate
        message: Button 10
    - service: switch.turn_on
      entity_id:
        - switch.basement_switch
        - switch.dining_room
        - switch.kitchen_back
        - switch.kitchen_front
        - switch.piano_back
        - switch.piano_front
        - switch.sunroom
    - service: mqtt.publish
      data:
        topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[6].b[10].bco'
        payload_template: '65504'
        retain: true
    - service: input_boolean.turn_on
      entity_id: input_boolean.controls_b10

- alias: HASwitchPlate_Controls_Button_11_On
  trigger:
    platform: mqtt
    topic: 'homeassistant/haswitchplate/HASwitchPlate/state/p[6].b[11]'
    payload: 'ON'
  condition:
    condition: state
    entity_id: input_boolean.controls_b11
    state: 'off'
  action:
    - service: logbook.log
      data_template:
        name: HASwitchPlate
        message: Button 11
    - service: switch.turn_on
      entity_id:
        - switch.back_flood
        - switch.Sunroom_Flood
        - switch.Kitchen_Patio
        - switch.Front_Porch
        - switch.jackie_bedroom
        - switch.upstairs_landing
        - switch.basement_switch
        - switch.dining_room
        - switch.kitchen_back
        - switch.kitchen_front
        - switch.piano_back
        - switch.piano_front
        - switch.sunroom
    - service: mqtt.publish
      data:
        topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[6].b[11].bco'
        payload_template: '65504'
        retain: true
    - service: input_boolean.turn_on
      entity_id: input_boolean.controls_b11



# ##########################################################################
# ##########################################################################
# ##########################################################################
# ##########################################################################
# ##########################################################################
# ##########################################################################
- alias: HASwitchPlate_Controls_Button_8_Off
  trigger:
    platform: mqtt
    topic: 'homeassistant/haswitchplate/HASwitchPlate/state/p[6].b[8]'
    payload: 'ON'
  condition:
    condition: state
    entity_id: input_boolean.controls_b8
    state: 'on'
  action:
    - service: logbook.log
      data_template:
        name: HASwitchPlate
        message: Button 8
    - service: switch.turn_off
      entity_id:
        - switch.back_flood
        - switch.Sunroom_Flood
        - switch.Kitchen_Patio
        - switch.Front_Porch
    - service: mqtt.publish
      data:
        topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[6].b[8].bco'
        payload_template: '65535'
        retain: true
    - service: input_boolean.turn_off
      entity_id: input_boolean.controls_b8

- alias: HASwitchPlate_Controls_Button_9_Off
  trigger:
    platform: mqtt
    topic: 'homeassistant/haswitchplate/HASwitchPlate/state/p[6].b[9]'
    payload: 'ON'
  condition:
    condition: state
    entity_id: input_boolean.controls_b9
    state: 'on'
  action:
    - service: logbook.log
      data_template:
        name: HASwitchPlate
        message: Button 9
    - service: switch.turn_off
      entity_id:
        - switch.jackie_bedroom
        - switch.upstairs_landing
    - service: mqtt.publish
      data:
        topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[6].b[9].bco'
        payload_template: '65535'
        retain: true
    - service: input_boolean.turn_off
      entity_id: input_boolean.controls_b9

- alias: HASwitchPlate_Controls_Button_10_Off
  trigger:
    platform: mqtt
    topic: 'homeassistant/haswitchplate/HASwitchPlate/state/p[6].b[10]'
    payload: 'ON'
  condition:
    condition: state
    entity_id: input_boolean.controls_b10
    state: 'on'
  action:
    - service: logbook.log
      data_template:
        name: HASwitchPlate
        message: Button 10
    - service: switch.turn_off
      entity_id:
        - switch.basement_switch
        - switch.dining_room
        - switch.kitchen_back
        - switch.kitchen_front
        - switch.piano_back
        - switch.piano_front
        - switch.sunroom
    - service: mqtt.publish
      data:
        topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[6].b[10].bco'
        payload_template: '65535'
        retain: true
    - service: input_boolean.turn_off
      entity_id: input_boolean.controls_b10

- alias: HASwitchPlate_Controls_Button_11_Off
  trigger:
    platform: mqtt
    topic: 'homeassistant/haswitchplate/HASwitchPlate/state/p[6].b[11]'
    payload: 'ON'
  condition:
    condition: state
    entity_id: input_boolean.controls_b11
    state: 'on'
  action:
    - service: logbook.log
      data_template:
        name: HASwitchPlate
        message: Button 11
    - service: switch.turn_off
      entity_id:
        - switch.back_flood
        - switch.Sunroom_Flood
        - switch.Kitchen_Patio
        - switch.Front_Porch
        - switch.jackie_bedroom
        - switch.upstairs_landing
        - switch.basement_switch
        - switch.dining_room
        - switch.kitchen_back
        - switch.kitchen_front
        - switch.piano_back
        - switch.piano_front
        - switch.sunroom
    - service: mqtt.publish
      data:
        topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[6].b[11].bco'
        payload_template: '65535'
        retain: true
    - service: input_boolean.turn_off
      entity_id: input_boolean.controls_b11
