# Button text/font
- alias: HASwitchPlate_Intercom
  trigger:
  - platform: mqtt
    topic: 'homeassistant/binary_sensor/HASwitchPlate/state'
    payload: 'ON'
  - platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[4].txt'
      payload: '"Jackie"'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[7].txt'
      payload: '"Isaac"'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[10].txt'
      payload: '"Alice"'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[13].txt'
      payload: '"Luke"'


- alias: HASwitchPlate_Jackie
  trigger:
    platform: mqtt
    topic: 'homeassistant/haswitchplate/HASwitchPlate/state/p[7].b[4]'
    payload: 'ON'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.intercom_alert_mode
        state: 'on'
      - condition: state
        entity_id: input_boolean.jackie
        state: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.jackie
    - service: script.speech_engine
      data_template:
        Intercom: "Jackie, Please come to the kitchen"

- alias: HASwitchPlate_Isaac
  trigger:
    platform: mqtt
    topic: 'homeassistant/haswitchplate/HASwitchPlate/state/p[7].b[7]'
    payload: 'ON'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.intercom_alert_mode
        state: 'on'
      - condition: state
        entity_id: input_boolean.isaac
        state: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.isaac
    - service: script.speech_engine
      data_template:
        Intercom: "Isaac, Please come to the kitchen"

- alias: HASwitchPlate_Alice
  trigger:
    platform: mqtt
    topic: 'homeassistant/haswitchplate/HASwitchPlate/state/p[7].b[10]'
    payload: 'ON'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.intercom_alert_mode
        state: 'on'
      - condition: state
        entity_id: input_boolean.alice
        state: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.alice
    - service: script.speech_engine
      data_template:
        Intercom: "alice, Please come to the kitchen"

- alias: HASwitchPlate_Luke
  trigger:
    platform: mqtt
    topic: 'homeassistant/haswitchplate/HASwitchPlate/state/p[7].b[4]'
    payload: 'ON'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.intercom_alert_mode
        state: 'on'
      - condition: state
        entity_id: input_boolean.luke
        state: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.luke
    - service: script.speech_engine
      data_template:
        Intercom: "Luke, Please come to the kitchen"

- alias: HASwitchPlate_Jackie_Reset
  trigger:
    - platform: state
      entity_id: input_boolean.jackie
      to: 'off'
      for:
        seconds: 5
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.jackie

- alias: HASwitchPlate_Isaac_Reset
  trigger:
    - platform: state
      entity_id: input_boolean.isaac
      to: 'off'
      for:
        seconds: 5
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.isaac

- alias: HASwitchPlate_Alice_Reset
  trigger:
    - platform: state
      entity_id: input_boolean.alice
      to: 'off'
      for:
        seconds: 5
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.alice

- alias: HASwitchPlate_Luke_Reset
  trigger:
    - platform: state
      entity_id: input_boolean.luke
      to: 'off'
      for:
        seconds: 5
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.luke
